# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: abjmorrison30
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: aaastorms
service: aaastormsETL

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  runtime: python3.9

layers:
  dependencies:
    path: ./
    name: aaastorms-dependencies
    description: Common dependencies for AAAStorms functions including geopandas
    compatibleRuntimes:
      - python3.9
    package:
      patterns:
        - requirements.txt
        - '!**'

  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 's3:PutObject'
            - 's3:GetObject'
            - 's3:ListBucket'
          Resource:
            - 'arn:aws:s3:::aaastorms-stormlogs'
            - 'arn:aws:s3:::aaastorms-stormlogs/*'
            - 'arn:aws:s3:::aaastorms-stormdata'
            - 'arn:aws:s3:::aaastorms-stormdata/*'
            - 'arn:aws:s3:::aaastorms-stormreports'
            - 'arn:aws:s3:::aaastorms-stormreports/*'
            - 'arn:aws:s3:::aaastorms-stormtriggers'
            - 'arn:aws:s3:::aaastorms-stormtriggers/*'
        - Effect: 'Allow'
          Action:
          - 'ses:*'
          Resource: 
          - '*'

functions:
  - ${file(./src/etl/etl.yml)}
  - ${file(./src/etlTriggers/etlTriggers.yml)}
  - ${file(./src/report/report.yml)}
