# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: abjmorrison30
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: aaastorms
service: aaastormsETL

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment: 
    BUILDX_NO_DEFAULT_ATTESTATIONS: 16
  ecr:
    images:
      etlImg:
        path: ./src/etl
        platform: linux/amd64
        provenance: false
      etlTriggersImg:
        path: ./src/etlTriggers
        platform: linux/amd64
        provenance: false
      reportImg:
        path: ./src/report
        platform: linux/amd64
        provenance: false

  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 's3:PutObject'
            - 's3:GetObject'
            - 's3:ListBucket'
          Resource:
            - 'arn:aws:s3:::aaastorms-stormlogs'
            - 'arn:aws:s3:::aaastorms-stormlogs/*'
            - 'arn:aws:s3:::aaastorms-stormdata'
            - 'arn:aws:s3:::aaastorms-stormdata/*'
            - 'arn:aws:s3:::aaastorms-stormreports'
            - 'arn:aws:s3:::aaastorms-stormreports/*'
            - 'arn:aws:s3:::aaastorms-stormtriggers'
            - 'arn:aws:s3:::aaastorms-stormtriggers/*'
        - Effect: 'Allow'
          Action:
          - 'ses:*'
          Resource: 
          - '*'

functions:
  - ${file(./src/etl/etl.yml)}
  - ${file(./src/etlTriggers/etlTriggers.yml)}
  - ${file(./src/report/report.yml)}

