
test_event = {
    "trigger_type": "pretrigger",
    "reason": [
      "storm_presence"
    ],
    "basin": "EP",
    "storm_data": {
      "uuid": "f60b3ad6b1394c6297252bc5f64650cf_EP022013",
      "name": "BARBARA",
      "id_noaa": "EP022013",
      "classification_noaa": "REMNANTS OF",
      "max_category": None,
      "current_windspeed_noaa": "25 mph",
      "max_sustainedwinds_noaa": "30 mph",
      "landfall_windspeed": None,
      "max_observed_windspeed": None,
      "est_stormsurge": None,
      "max_stormsurge_adam": None,
      "rainfall_report_adam": None,
      "wind_report_adam": None,
      "gdacs_alert_level_adam": None,
      "countries_adam": None,
      "subnational_impacts_adam": None,
      "watches_noaa": [],
      "warnings_noaa": [],
      "windforecast_noaa": {
        "status": False,
        "time_of_forecast": "",
        "forecast": [],
        "exception_code": "\"None of [Index(['VALIDTIME', 'NE', 'NW', 'SE', 'SW'], dtype='object')] are in the [columns]\""
      },
      "summary_link_noaa": "http://www.nhc.noaa.gov/text/refresh/MIATCPEP2+shtml/302031.shtml",
      "summary_noaa": "\n\n\n842 \nWTPZ32 KNHC 011812\nTCPEP2\n\nBULLETIN\nRemnants Of Beatriz Special Advisory Number  12\nNWS National Hurricane Center Miami FL       EP022023\n1200 PM MDT Sat Jul 01 2023\n\n...BEATRIZ DISSIPATES OFF THE WEST-CENTRAL COAST OF MEXICO...\n...THIS IS THE LAST ADVISORY...\n\n\nSUMMARY OF 1200 PM MDT...1800 UTC...INFORMATION\n-----------------------------------------------\nLOCATION...20.7N 106.2W\nABOUT 40 MI...60 KM WNW OF CABO CORRIENTES MEXICO\nABOUT 55 MI...90 KM SSE OF LAS ISLAS MARIAS MEXICO\nMAXIMUM SUSTAINED WINDS...30 MPH...45 KM/H\nPRESENT MOVEMENT...NW OR 315 DEGREES AT 12 MPH...19 KM/H\nMINIMUM CENTRAL PRESSURE...1008 MB...29.77 INCHES\n\n\nWATCHES AND WARNINGS\n--------------------\nCHANGES WITH THIS ADVISORY:\n\nThe government of Mexico has discontinued all watches and warnings\nfor the west-central coast of mainland Mexico.\n\nSUMMARY OF WATCHES AND WARNINGS IN EFFECT:\n\nThere are no coastal watches or warnings in effect.\n\n\nDISCUSSION AND OUTLOOK\n----------------------\nSatellite-derived wind data indicate the Beatriz no longer has a\nsurface circulation and has dissipated.  At 1200 PM MDT (1800 UTC),\nthe remnants of Beatriz were located near latitude 20.7 North,\nlongitude 106.2 West. The remnants are moving toward the northwest\nnear 12 mph (19 km/h), but are expected to slow down and meander\nover the mouth of the Gulf of California during the next few days.\n\nMaximum sustained winds have decreased to near 30 mph (45 km/h) with\nhigher gusts.\n\nThe estimated minimum central pressure is 1008 mb (29.77 inches).\n\n\nHAZARDS AFFECTING LAND\n----------------------\nRAINFALL:  Through Monday, storm total rainfall of 3 to 5 inches,\nwith maximum amounts of 8 inches, is expected across portions of\nsouthern and western Mexico from Colima northwest to Sinaloa and\nDurango in association with the remnants of Beatriz.  This rainfall\ncould lead to localized flash flooding and mudslides.\n\nSURF:  Swells generated by Beatriz are expected to diminish along\nthe southwestern coast of Mexico during the next day or so.  These\nswells could cause life-threatening surf and rip current conditions.\nPlease consult products from your local weather office.\n\n\nNEXT ADVISORY\n-------------\nThis is the last public advisory issued by the National Hurricane\nCenter on this system.  For additional information on the remnants \nof Beatriz please see High Seas Forecasts issued by the National \nWeather Service, under AWIPS header NFDHSFEPI, WMO header FZPN02 \nKWBC, and on the web at ocean.weather.gov/shtml/NFDHSFEPI.php\n\n\n$$\nForecaster Berg\n\n\n\n",
      "current_position": None,
      "report_date_noaa": "2013-05-30 20:32:00",
      "report_date_adam": None
    },
    "subhazards": [],
    "initial_report": False,
    "refactivity": {
      "ActivityArn": "arn:aws:states:us-east-1:581736746758:activity:StormReference",
      "CreationDate": "2023-07-05T15:34:09.866Z"
    }
  }
